### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ilhuicatl** [hayderux/electron-quick-start-flutter#4]
webdev tool is not available for flutter compilation and it launches this error

```> webdev build

Unhandled exception:       
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: C:\Program Files\Dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:70:5)
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)
#2      readPubspecLock (package:webdev/src/command/shared.dart:63:39)
#3      BuildCommand.run (package:webdev/src/command/build_command.dart:51:29)
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///C:/Users/new_m/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-2.5.3/bin/webdev.dart:17:22)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: C:\Program Files\Dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:70:5)
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)
#2      readPubspecLock (package:webdev/src/command/shared.dart:63:39)
#3      BuildCommand.run (package:webdev/src/command/build_command.dart:51:29)
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///C:/Users/new_m/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-2.5.3/bin/webdev.dart:17:22)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! electron-quick-start-flutter@1.0.0 build: `webdev build`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the electron-quick-start-flutter@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\---\AppData\Roaming\npm-cache\_logs\2020-03-03T02_16_23_547Z-debug.log

**Comment by ilhuicatl** [comment]
my log file says
```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle electron-quick-start-flutter@1.0.0~prebuild: electron-quick-start-flutter@1.0.0
6 info lifecycle electron-quick-start-flutter@1.0.0~build: electron-quick-start-flutter@1.0.0
7 verbose lifecycle electron-quick-start-flutter@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle electron-quick-start-flutter@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\new_m\Documents\GitHub\flutter\electron-quick-start-flutter\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\Dart\dart-sdk\bin;C:\Program Files\Git\cmd;C:\src\flutter\bin;C:\Users\new_m\AppData\Roaming\Pub\Cache\bin;C:\Program Files\Pandoc\;C:\Program Files (x86)\Dev-Cpp\MinGW64\bin;C:\Program Files\MATLAB\R2019b\bin;C:\Users\new_m\AppData\Local\Microsoft\WindowsApps;C:\Users\new_m\AppData\Roaming\npm;C:\Users\new_m\AppData\Local\Programs\Microsoft VS Code\bin;C:\win-builds\bin;C:\Users\new_m\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle electron-quick-start-flutter@1.0.0~build: CWD: C:\Users\new_m\Documents\GitHub\flutter\electron-quick-start-flutter
10 silly lifecycle electron-quick-start-flutter@1.0.0~build: Args: [ '/d /s /c', 'webdev build' ]
11 silly lifecycle electron-quick-start-flutter@1.0.0~build: Returned: code: 255  signal: null
12 info lifecycle electron-quick-start-flutter@1.0.0~build: Failed to exec build script
13 verbose stack Error: electron-quick-start-flutter@1.0.0 build: `webdev build`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid electron-quick-start-flutter@1.0.0
15 verbose cwd C:\Users\new_m\Documents\GitHub\flutter\electron-quick-start-flutter
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 255
22 error electron-quick-start-flutter@1.0.0 build: `webdev build`
22 error Exit status 255
23 error Failed at the electron-quick-start-flutter@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]

**Comment by hayderux** [comment]
fixed in latest commit
